kitty/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

urlpatterns = patterns('',
    # Welcome Page:
    url(r'^$', 'kitty.views.home', name='home'),
    # creating a kitty
    url(r'^create/', 'kitty.views.create', name='create'),
    # display item Modal
    url(r'^(?P<id>\w{5})/itemModal/(?P<itemID>\d+)/', 'kitty.views.itemModal'),
    # display user Modal
    url(r'^(?P<id>\w{5})/userModal/(?P<userID>\d+)/', 'kitty.views.userModal'),
    # display kitty with ID
    url(r'^(?P<id>\w{5})/', 'kitty.views.show'),
    # for setting language
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # Dajax
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    
    # url(r'^kitty/', include('kitty.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

# API URLS
urlpatterns += patterns('kitty.api',
    url(r'^api/incItem/(?P<user_item_id>\d+)', 'incItem'),
    url(r'^api/decItem/(?P<user_item_id>\d+)', 'decItem'),
    url(r'^api/userItems/(?P<user_id>\d+)', 'userItems'),
    url(r'^api/users/(?P<id>\w{5})/', 'users'),
    url(r'^api/kitty/(?P<id>\w{5})/', 'kitty'),
)

kitty/models.py
from randomprimary.random_primary import RandomPrimaryIdModel
from django.db import models
from django import forms

# every Kitty has a Random ID
class Kitty(RandomPrimaryIdModel):
    name = models.CharField(max_length=50)
    created_by = models.CharField(max_length=50)

# Form for creating a Kitty
class KittyForm(forms.ModelForm):

    class Meta:
        model = Kitty
        fields = ['name','created_by']

# every Kitty has Items (e.g. a drink, coffee, snack)
class Item(models.Model):
    kitty = models.ForeignKey(Kitty)
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    EAN = models.CharField(max_length=13, null=True, blank=True)
    quantity = models.IntegerField(max_length=5)

# Form for creating an Item
class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ['name','price','EAN','quantity']

# every Kitty has users with money (can be negative)
class KittyUser(models.Model):
    kitty = models.ForeignKey(Kitty)
    name = models.CharField(max_length=50)
    money = models.DecimalField(max_digits=5, decimal_places=2)

# Form for creating a KittyUser
class KittyUserForm(forms.ModelForm):

    class Meta:
        model = KittyUser
        fields = ['name','money']

# connection between user <-> items
# stores users item consumption as quantity 
class UserItem(models.Model):
    item = models.ForeignKey(Item)
    quantity = models.IntegerField(max_length=5)
    user = models.ForeignKey(KittyUser)

kitty/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.utils.translation import gettext as _
from django.utils import translation
from kitty.models import KittyForm, Kitty, Item, ItemForm, KittyUser, KittyUserForm
from django.db.models import Sum
from django.conf import settings

LANGUAGES = (
  ('de', _('German')),
  ('en', _('English')),
)

def home(request):
    return render(request, 'welcome_page.html', {'LANGUAGES':LANGUAGES,})

def create(request):
    if request.method == 'POST':
        form = KittyForm(request.POST)
        if form.is_valid():
            newKitty = form.save()
            return HttpResponseRedirect('../%s' % newKitty.id)
    else:
        form = KittyForm()
    return render(request, 'create.html', {'LANGUAGES':LANGUAGES, 'form':form,})

def show(request, id):
    k = Kitty.objects.get(id=id) # requested kitty
    i = Item.objects.filter(kitty=k).annotate(Sum('useritem__quantity')) # items
    u = KittyUser.objects.filter(kitty=k) # kitty user
    i_form = ItemForm()
    u_form = KittyUserForm()
    return render(request, 'show.html', {  'LANGUAGES':LANGUAGES,
                                            'title': k.name, 
                                            'k':k, 
                                            'i':i, 
                                            'i_form':i_form,
                                            'u':u,
                                            'u_form':u_form,
                                            's_io_server': settings.SOCKET_IO_SERVER,
                                            's_io_port': settings.SOCKET_IO_PORT,})

def itemModal(request, id, itemID):
    item = Item.objects.filter(kitty_id=id).get(id=itemID)
    form = ItemForm(instance=item)

    return render(request, 'modal_view.html', {'identifier':"editItem",
                                               'title':_("edit item"), 
                                               'form':form,
                                               'k_id':id,
                                               'onSave':"editItem(%s);"%itemID})

def userModal(request, id, userID):
    user = KittyUser.objects.filter(kitty_id=id).get(id=userID)
    form = KittyUserForm(instance=user)

    return render(request, 'modal_view.html', {'identifier':"editUser",
                                               'title':_("edit user"), 
                                               'form':form,
                                               'k_id':id,
                                               'onSave':"editUser(%s);"%userID})

templates/create.html
{% extends "master.html" %}

{% load i18n %}
{% load staticfiles %}
{% load addcss_filter %}

{% block content %}
<form class="form-horizontal" role="form" action="" method="post">
{% csrf_token %}

{{ form.non_field_errors }}

{% for field in form %}
  <div class="form-group">
    <label class="col-sm-2 control-label" for="id_{{field.html_name}}">{{field.label}}</label>
    <div class="col-sm-5">
      {{ field |addcss:"form-control"}}
      {% for error in field.errors %}
        <strong>{{ error|escape }}</strong>
      {% endfor %}
    </div>
  </div> 
{% endfor %}

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn">{% trans "Create"%}</button>
    </div>
</div>
</form>
{% endblock %}

templates/master.html
{% load i18n %}
{% load staticfiles %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'bootstrap/jumbotron-narrow.css' %}" rel="stylesheet">
{% block head %}{% endblock %}

 <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li class="active"><a href="{% url 'home' %}">Home</a></li>
        </ul>
        <h3 class="text-muted">{{ title|default:"pyKitty" }}</h3>
      </div>
      {% block content %} {% endblock %}

      <div class="footer">
        <form action="{% url 'set_language' %}" method="post" class="form-inline" role="form">
			{% csrf_token %}
			<input name="next" type="hidden" value="{{ redirect_to }}" />
            <div class="form-group">
			<select name="language" class="form-control input-sm" style="width: 150px">
				{% get_language_info_list for LANGUAGES as languages %}
				{% for language in languages %}
					<option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
					    {{ language.name_local }} ({{ language.code }})
					</option>
				{% endfor %}
			</select>
            </div>
            <div class="form-group">
            <button type="submit" class="btn btn-default">Go</button>
            </div>
		</form>
      </div>

 </div>
<!-- /container -->

{% block modals%}{% endblock %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block script %}{% endblock %}

templates/modal_view.html
{% load addcss_filter %}

<!-- {{identifier}}Modal -->
<div class="modal fade" id="{{identifier}}Modal" tabindex="-1" role="dialog" aria-labelledby="{{identifier}}ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="{{identifier}}ModalLabel">{{title}}</h4>
      </div>
      <div class="modal-body">
        <form method="post" action="" id="id_{{identifier}}_form" class="form-horizontal" role="form">{% csrf_token %}
        <input type="hidden" name="kitty_id" value="{{k_id}}">
          {% for field in form %}
          <div class="form-group">
          <label class="col-sm-2 control-label" for="id_{{field.html_name}}">{{field.label}}</label>
            <div class="col-sm-5">
              {{ field |addcss:"form-control"}}
              {% for error in field.errors %}
                <strong>{{ error|escape }}</strong>
              {% endfor %}
            </div>
          </div> 
        {% endfor %}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onClick="{{onSave}}">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/show.html
{% extends "master.html" %}

{% load i18n %}
{% load staticfiles %}
{% load subtract_filter %}
{% load dajaxice_templatetags %}

{% block script %}
<script src="{% static 'jquery/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
{% dajaxice_js_import %}
<script src="{% static '/static/dajax/jquery.dajax.core.js' %}"></script>
<script src="http://{{s_io_server}}:{{s_io_port}}/socket.io/socket.io.js"></script>
<script>
    function incItem(item_id){
        Dajaxice.kitty.incItem(Dajax.process,{'item_id':item_id});
    }
    function decItem(item_id){
        Dajaxice.kitty.decItem(Dajax.process,{'item_id':item_id});
    }
    function itemModal(item_id){
        $("#id_other_modal").load("./itemModal/"+item_id+"/", function() {
            $("#editItemModal").modal('show');
        });
    }
    function userModal(user_id){
        $("#id_other_modal").load("./userModal/"+user_id+"/", function() {
            $("#editUserModal").modal('show');
        });
    }
</script>
<script>
// socket.io
    var socket = io.connect('{{s_io_server}}', {port: {{s_io_port}}});
        $(document).ready(function(){
            
            socket.on('connect', function(){
                socket.emit ('join_room', '{{k.id}}');
                console.log("join room: {{k.id}}");
            });

            socket.on('new_user', function(json_data) {
                var html_string = '<tr id="id_user_'+json_data.id+'">';
                html_string = html_string + '<td><a href="#" onclick="userModal('+json_data.id+');" id="id_user_name_'+json_data.id+'">'+json_data.name+' ('+json_data.money.toFixed(2)+' EUR)</a></td>';

                var user_items = jQuery.parseJSON(json_data.user_items);

                for (i in user_items) {
                    html_string = html_string + '<td style="text-align:right;"><span id="id_user_item_'+user_items[i].pk+'">'+user_items[i].fields.quantity+'</span> <div class="btn-group btn-group-vertical"><button class="btn btn-default btn-sm" onclick="incItem('+user_items[i].pk+');"><span class="glyphicon glyphicon-chevron-up"></span></button><button class="btn btn-default btn-sm" onclick="decItem('+user_items[i].pk+');"><span class="glyphicon glyphicon-chevron-down"></span></button></div></td>';
                }
                html_string = html_string + "</tr>";
                
                $(html_string).hide().appendTo('#id_user_table').fadeIn();
            });

            socket.on('new_item', function(json_data) {
                var html_string = '<th style="text-align:right;"><a href="#" onclick="itemModal('+json_data.item_id+');"><strong>'+json_data.item_name+'</strong> <br/> ('+json_data.item_price.toFixed(2)+' EUR)</a></th>'
                $(html_string).hide().appendTo('#id_item_name_table').fadeIn();
                var user_items = jQuery.parseJSON(json_data.user_items);

                for (i in user_items) {
                    html_string = '<td style="text-align:right;"><span id="id_user_item_'+user_items[i].pk+'">'+user_items[i].fields.quantity+'</span> <div class="btn-group btn-group-vertical"><button class="btn btn-default btn-sm" onclick="incItem('+user_items[i].pk+');"><span class="glyphicon glyphicon-chevron-up"></span></button><button class="btn btn-default btn-sm" onclick="decItem('+user_items[i].pk+');"><span class="glyphicon glyphicon-chevron-down"></span></button></div></td>';
                    $(html_string).hide().appendTo('#id_user_'+user_items[i].fields.user).fadeIn();
                }
                html_string = '<th style="text-align:right;" id="id_item_quantity_'+json_data.item_id+'">'+json_data.item_quantity+'</th>'
                $(html_string).hide().appendTo('#id_item_quantity').fadeIn();
                html_string = '<th style="text-align:right;" id="id_item_quantity_consumed_'+json_data.item_id+'">0</th>'
                $(html_string).hide().appendTo('#id_item_quantity_consumed').fadeIn();
                html_string = '<th style="text-align:right;" id="id_item_quantity_available_'+json_data.item_id+'">'+json_data.item_quantity+'</th>'
                $(html_string).hide().appendTo('#id_item_quantity_available').fadeIn();

            });

            socket.on('update_user_item', function(json_data) {
                $('#id_user_item_' + json_data.user_item_id).html(json_data.user_item_quantity);
                $('#id_user_name_'+ json_data.user_id).html(json_data.user_name+' ('+json_data.user_money.toFixed(2)+' EUR)');
                $('#id_item_quantity_consumed_'+ json_data.item_id).html(json_data.item_quantity_sum);
                $('#id_item_quantity_available_'+ json_data.item_id).html(json_data.item_quantity-json_data.item_quantity_sum);
            });

        });
</script>
{% endblock %}

{% block modals %}
    <script>
        function addItem() {
        Dajaxice.kitty.addItem(Dajax.process,{'form':$('#id_newItem_form').serialize(true)});
        }
    </script>
    {% include "modal_view.html" with identifier="newItem" k_id=k.id title="New Item" form=i_form onSave="addItem();" %}
    <script>
        function addUser() {
        Dajaxice.kitty.addUser(Dajax.process,{'form':$('#id_newUser_form').serialize(true)});
        }
    </script>
    {% include "modal_view.html" with identifier="newUser" k_id=k.id title="New User" form=u_form onSave="addUser();" %}
    <script>
        function editItem(item_id) {
        Dajaxice.kitty.editItem(Dajax.process,{'form':$('#id_editItem_form').serialize(true),
                                               'item_id':item_id});
        }
    </script>
    <script>
        function editUser(user_id) {
        Dajaxice.kitty.editUser(Dajax.process,{'form':$('#id_editUser_form').serialize(true),
                                               'user_id':user_id});
        }
    </script>
    <div id="id_other_modal"></div>
{% endblock %}

{% block content %}

<div style="height: 100px;">
  <p>{% blocktrans  with k.created_by as created_by %}
    Kitty was created by {{created_by}}.
    {% endblocktrans %}</p>

  <a href="#newItemModal" role="button" class="btn btn-primary" data-toggle="modal"><i class="icon-glass icon-white"></i> {% trans "new Item"%}</a>
  <a href="#newUserModal" role="button" class="btn btn-primary" data-toggle="modal"><i class="icon-user icon-white"></i> {% trans "new User"%}</a>
</div>

</div>
<div class="container-full">
<table class="table table-striped table-hover">
    <thead>
        <tr id="id_item_name_table">
                <th>{% trans "Name (balance)"%}</th>
                {% for item in i %}
                    <th style="text-align:right;"><a href="#" onclick="itemModal({{item.id}});"><strong>{{item.name}}</strong> <br/> ({{item.price|floatformat:2}} EUR)</a></th>
                {% endfor %}
        </tr>
    </thead>
    <tbody id="id_user_table">
        {% for user in u %}
            <tr id="id_user_{{user.id}}">
                <td>
                    <a href="#" onclick="userModal({{user.id}});" id="id_user_name_{{user.id}}">{{user.name}} ({{user.money|floatformat:2}} EUR)</a>
                </td>
                {% for userItem in user.useritem_set.all %}
                <td style="text-align:right;"><span id="id_user_item_{{userItem.id}}">{{userItem.quantity}}</span> 
                    <div class="btn-group btn-group-vertical">
                        <button class="btn btn-default btn-sm" onclick="incItem({{userItem.id}});"><span class="glyphicon glyphicon-chevron-up"></span></button>
                        <button class="btn btn-default btn-sm" onclick="decItem({{userItem.id}});"><span class="glyphicon glyphicon-chevron-down"></span></button>
                    </div>
                </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </tr>
  </tbody>
  <tfoot>
    <tr id="id_item_quantity">
        <th>{% trans "item quantity" %}</th>
        {% for item in i %}
        <th style="text-align:right;" id="id_item_quantity_{{item.id}}">{{item.quantity}}</th>
        {% endfor %}
    </tr>
    <tr id="id_item_quantity_consumed">
        <th>{% trans "consumed items" %}</th>
        {% for item in i %}
        <th style="text-align:right;" id="id_item_quantity_consumed_{{item.id}}">{{item.useritem__quantity__sum}}</th>
        {% endfor %}    
    </tr>
    <tr id="id_item_quantity_available">
        <th>{% trans "available items" %}</th>
        {% for item in i %}
        <th style="text-align:right;" id="id_item_quantity_available_{{item.id}}">{{item.quantity|subtract:item.useritem__quantity__sum}}</th>
        {% endfor %}
    </tr>
  </tfoot>
</table>
{% endblock %}

templates/welcome_page.html
{% extends "master.html" %}

{% load i18n %}
{% load staticfiles %}

{% block content %}
<div class="jumbotron"> 
  <h1>{% trans "a new Kitty ..." %}</h1>
  <p>&nbsp;</p>
  <a class="btn btn-large btn-success" href="{% url 'create' %}">{% trans "create it now" %}</a>
</div>
{% endblock %}